# Generated by Django 3.0.7 on 2022-05-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='ContenidoMedicamento',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='DescripcionMedicamento',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='FabricanteMedicamento',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='contenidoMedicamento',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Contenido'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='descripcionMedicamento',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='fabricanteMedicamento',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Fabricante'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='imagenPublicacion',
            field=models.ImageField(blank=True, null=True, upload_to='fotopublicaciones', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True, verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='gramaje',
            field=models.IntegerField(blank=True, null=True, verbose_name='gramaje'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='nombreMedicamento',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Nombre'),
        ),
    ]
