# Generated by Django 3.0.7 on 2022-05-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0002_auto_20220508_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='codigo')),
                ('nombrePersona', models.CharField(blank=True, max_length=40, null=True, verbose_name='nombrePersona')),
                ('Sintomas', models.CharField(blank=True, max_length=40, null=True, verbose_name='sintomas')),
                ('diagnostico', models.CharField(blank=True, max_length=40, null=True, verbose_name='diagnostico')),
                ('medicamentoRecetado', models.CharField(blank=True, max_length=40, null=True, verbose_name='medicamentoRecetado')),
            ],
        ),
    ]
