# Generated by Django 3.0.7 on 2022-05-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0003_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='Sintomas',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='sintomas'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='diagnostico',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='diagnostico'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='medicamentoRecetado',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='medicamento Recetado'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='nombrePersona',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='nombre del paciente'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='codigo',
            field=models.AutoField(max_length=5, primary_key=True, serialize=False, verbose_name='codigo'),
        ),
    ]
