# Generated by Django 3.0.7 on 2022-05-08 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0005_auto_20220508_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('codigo2', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('nombrePersona', models.CharField(blank=True, max_length=40, null=True, verbose_name='nombre del paciente')),
                ('Sintomas', models.TextField(blank=True, max_length=300, null=True, verbose_name='sintomas')),
                ('diagnostico', models.TextField(blank=True, max_length=300, null=True, verbose_name='diagnostico')),
                ('medicamentoRecetado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppWeb.Medicamento')),
            ],
        ),
    ]
