# Generated by Django 3.0.7 on 2022-05-08 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0006_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='Sintomas',
            field=models.TextField(max_length=300, null=True, verbose_name='sintomas'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='codigo2',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='diagnostico',
            field=models.TextField(max_length=300, null=True, verbose_name='diagnostico'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='medicamentoRecetado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppWeb.Medicamento'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='nombrePersona',
            field=models.CharField(max_length=40, verbose_name='nombre del paciente'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='cantidad',
            field=models.IntegerField(null=True, verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='contenidoMedicamento',
            field=models.CharField(max_length=40, null=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='descripcionMedicamento',
            field=models.CharField(max_length=40, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='fabricanteMedicamento',
            field=models.CharField(max_length=40, null=True, verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='gramaje',
            field=models.IntegerField(null=True, verbose_name='gramaje'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='imagenPublicacion',
            field=models.ImageField(null=True, upload_to='fotopublicaciones'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='nombreMedicamento',
            field=models.CharField(max_length=40, null=True, verbose_name='Nombre'),
        ),
    ]
