# Generated by Django 3.0.7 on 2022-05-11 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0007_auto_20220508_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='medicamentoRecetado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppWeb.Medicamento'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='cantidad',
            field=models.IntegerField(null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='gramaje',
            field=models.IntegerField(null=True, verbose_name='Gramaje'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='nombreMedicamento',
            field=models.CharField(max_length=40, null=True, verbose_name='Nombre del medicamento'),
        ),
        migrations.CreateModel(
            name='RetiroMedicamento',
            fields=[
                ('codigoRetiro', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.TextField(max_length=10, null=True, verbose_name='Rut de la persona que retira')),
                ('nombrePersona', models.CharField(max_length=40, null=True, verbose_name='Nombre de la persona que retira')),
                ('apellidoPersona', models.CharField(max_length=40, null=True, verbose_name='Apellido de la persona que retira')),
                ('cantidad', models.IntegerField(null=True, verbose_name='Cantidad')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppWeb.Medicamento')),
            ],
        ),
    ]
