# Generated by Django 3.0.7 on 2022-05-11 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0016_auto_20220510_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='rut',
            field=models.CharField(max_length=10, null=True, verbose_name='Rut del paciente'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='Sintomas',
            field=models.TextField(max_length=300, null=True, verbose_name='Sintomas'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='diagnostico',
            field=models.TextField(max_length=300, null=True, verbose_name='Diagnostico'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='medicamentoRecetado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppWeb.Medicamento', verbose_name='Medicamento'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='nombrePersona',
            field=models.CharField(max_length=40, null=True, verbose_name='Nombre del paciente'),
        ),
        migrations.AlterField(
            model_name='retiro',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppWeb.Medicamento'),
        ),
    ]
