# Generated by Django 4.0.1 on 2022-05-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0018_auto_20220510_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='precio',
            field=models.IntegerField(null=True, verbose_name='Precio'),
        ),
    ]
