# Generated by Django 4.0.1 on 2022-05-19 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0019_medicamento_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicamento',
            old_name='nombreMedicamento',
            new_name='nombre',
        ),
    ]
