# Generated by Django 3.0.7 on 2022-05-21 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0021_auto_20220520_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicamento',
            old_name='codigo',
            new_name='id',
        ),
    ]
