# Generated by Django 4.0.1 on 2022-06-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0022_auto_20220520_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='caducado',
            field=models.CharField(max_length=2, null=True, verbose_name='caducar'),
        ),
    ]
